name: Build and Push Images

on:
  pull_request:
    branches:
      - develop
    types:
      - opened
      - reopened
      - synchronize
      - closed
    inputs:
      name:
        description: The image name
        required: true
        type: string
      tags:
        description: The image tags
        required: true
        type: string
jobs:
  build-develop-merge:
    if: github.base_ref == 'develop' && github.event.pull_request.merged == false
    uses: .github/workflows/reusable_build-push.yml@DEVOPS-1410-ui-builds
    with:
      name: '${{ github.event.repository.name }}-develop'
      tags: pr-${{ github.event.number }},latest
    secrets: inherit
